package fr.fxjavadevblog;

import org.jboss.weld.junit5.EnableWeld;
import org.jboss.weld.junit5.WeldInitiator;
import org.jboss.weld.junit5.WeldSetup;
import org.junit.Assert;
import org.junit.jupiter.api.Test;

import lombok.extern.slf4j.Slf4j;

import javax.inject.Inject;

/**
 * simple test class for the VideoGameRepository, using LOMBOK and WELD.
 *
 * @author robin
 */

@Slf4j
@EnableWeld
class VideoGameRepositoryTest
{
	@WeldSetup // This is need to discover Producers and DeltaSpike Repository functionality
	private WeldInitiator weld = WeldInitiator.performDefaultDiscovery();

	@Inject
	private VideoGameRepository repo;

	@Test
	void test()
	{

		VideoGame videoGame = VideoGameFactory.newInstance();
		videoGame.setName("XENON");
		repo.save(videoGame);
		// testing if the ID field had been generated by the JPA Provider.
		Assert.assertNotNull(videoGame.getVersion());
		Assert.assertTrue(videoGame.getVersion() > 0);
		log.info("Video Game : {}", videoGame);
	}

}
