package fr.fxjavadevblog;

import org.apache.deltaspike.data.api.EntityRepository;
import org.apache.deltaspike.data.api.Repository;


@Repository
public interface VideoGameRepository extends EntityRepository <VideoGame, Long>
{
    // nothing to code here : automatic Repo generated by DeltaSpike
}
